@startuml mengundang tamu

    title "Mengundang Tamu"
    hide footbox
    skinparam shadowing false
    skinparam sequence {    
        ArrowThickness 1.5
        ActorFontName Century Gothic
        ActorBackgroundColor  #C6EFFC
        ArrowFontName Century Gothic
        ParticipantBorderThickness 1.5
        ParticipantBackgroundColor #C6EFFC
    }

    actor "Penyelenggara Event" as eo
    participant "__:GuestScreen__" as viewGuest
    participant "__:GuestController__" as controllerGuest
    participant "__:Get__" as libGet
    participant "__:ApiGuest__" as apiGuest
    participant "__:ApiUtil__" as apiUtil
    participant "__:EventGuestController__" as controllerGuestBackend
    participant "__:EmailService__" as serviceEmail
    participant "__:EventRepository__" as repositoryEvent
    participant "__:EventGuestRepository__" as repositoryGuest
    participant "__:JavaMailMessage__" as libMail

    eo -> viewGuest: Mengklik tombol undang
    activate eo
    activate viewGuest
    viewGuest -> controllerGuest: .inviteAllGuest()
    activate controllerGuest
    controllerGuest --> viewGuest: .dialog()
    viewGuest --> eo: Menampilkan konfirmasi
    eo -> viewGuest: Mengklik tombol OK
    controllerGuest -> apiGuest: .inviteAllGuest(eventId)
    activate apiGuest
    apiGuest -> apiUtil: .apiRequestGet(endpoint)
    activate apiUtil
    apiUtil -> controllerGuestBackend: HTTP Request
    activate controllerGuestBackend
    controllerGuestBackend -> serviceEmail: .inviteAll(eventId)
    activate serviceEmail
    serviceEmail -> repositoryEvent: .findById(eventId)
    activate repositoryEvent
    repositoryEvent --> serviceEmail: eventData
    deactivate repositoryEvent
    serviceEmail -> repositoryGuest: .findById(eventId)
    activate repositoryGuest
    repositoryGuest --> serviceEmail: eventGuest
    serviceEmail ->  serviceEmail: .mailMessage(eventData)
    activate serviceEmail
    deactivate serviceEmail
    serviceEmail ->  serviceEmail: .generateIcs(eventData)
    activate serviceEmail
    deactivate serviceEmail
    serviceEmail ->  libMail: .createMimeMessage()
    activate libMail
    libMail --> serviceEmail: message
    loop add multiple email
        serviceEmail -> serviceEmail: .add(email)
    end
    serviceEmail ->  libMail: .send(message)
    deactivate 
    serviceEmail -> repositoryGuest: .save(eventGuest)
    deactivate repositoryGuest
    deactivate serviceEmail 
    controllerGuestBackend --> apiUtil: JSON Response
    deactivate
    apiUtil --> apiGuest: response
    deactivate
    apiGuest --> controllerGuest: response
    deactivate 
    controllerGuest -> libGet: .defaultDialog()
    activate libGet
    libGet --> viewGuest: Alert Dialog
    viewGuest --> eo: Menampilkan pesan status
    eo -> viewGuest: Mengklik tombol OK
    viewGuest -> controllerGuest: .back()
    controllerGuest -> libGet: .back()
    deactivate
@enduml